version: '3'
services:
  web:
    ports:
      - "28000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: webapi.test_settings
  db:
    ports:
      - "23306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_test
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_pass