version: '3'
services:
  web:
    ports:
      - "18000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: cms.development_settings
  db:
    ports:
      - "33306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_dev
      MYSQL_DATABASE: dev_db
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: dev_pass